### ISSUE TITLE
Template errors in GCC/G++

### ISSUE THREAD

**Issue by jammy4536** [thinks/poisson-disk-sampling#1]
Tried to use this library, but in testing if it works on my machine with the sample syntax, the header file gives a series of errors relating to the templates. They seem to be issues that aren't present in Visual Studio, but present in GCC or Clang. 
I tried to fix the issues as the compiler suggests, and it now compiles, however doesn't provide any output. I've checked that the inputs are correct and not mangled, so its surely something in the library. Any ideas what's happening?

**Comment by thinks** [comment]
Hi Jamie,

Glad you want to use my code, and thanks for bringing this to my attention.
I compiled the code using the clang toolset and I did indeed get a few
errors related to template syntax. I've fixed those and the changes have
been pushed. I also ran the examples and I seem to be getting values, so
I'm not sure what the problem is there. I get values after building with
both MSVC and clang. Let me know if you're not able to sort it out, you
should always get at least one sample.

Best,

T

**Comment by thinks** [comment]
That template parameter shadowing sure does look quite suspicious... I will have a look at it this evening. 

If you flip x_min and x_max such that x_max < x_min an exception should be thrown? I have tried to verify the inputs to make sure this type of bug is hard to write.

**Comment by jammy4536** [comment]
Just done my own little test. The exception is thrown when one of the bounds fails to satisfy, but not both. e.g.
` const std::array<float,2> xmin = {-10.0,10.0};
const std::array<float,2> xmax = {10.0,-10.0};` 
Exception thrown.

`const std::array<float,2> xmin = {10.0,10.0};
const std::array<float,2> xmax = {-10.0,-10.0};`
No exception.

**Comment by thinks** [comment]
Added plenty of warnings for both MSVC and GNU/clang compilers. Strangely the clang compiler still didn't catch that template parameter shadowing, but I tried to fix that too. I don't have access to a Linux machine right now, so it's hard to test the GNU compilation. If you have time, let me know how you get on.

I tried to reproduce the exception behaviour, but on MSVC and clang the code seems fine. I added an extra test, but I was never able to reproduce the failure.

**Comment by jammy4536** [comment]
Okay I think the failure to catch is something to do with Cygwin. I've just tested it on MinGW and it caught the double negative. For some reason Cygwin fails to catch it, but doesn't cause further issues. 
But the library now works on GCC without issue!

**Comment by jammy4536** [comment]
As a side, my application of the library is to try create particles near other ones that already exist, and I was wondering how difficult it would be to implement passing a vector of pre-existing particles to the library? This would then save huge amounts of effort checking for neighbours and then deleting. 
Didn't open another issue since it is quite off-topic!

**Comment by thinks** [comment]
The problem your describe is interesting and may not be that hard to solve. Instead of starting with an empty domain, you have some samples already (i'll assume those samples are "nicely" spaced). My first idea would be to just add those existing samples and then use one of them to "spread" from. If you have a look at the one page sketch describing the method in this repo you'll see what I mean.

Btw, there was indeed a horrendous bug in the bounds checking code. Your reporting was probably correct and I didn't try hard enough when reproducing. Anyhow, I've fixed it now.
