### ISSUE TITLE
How to generate from custom polygon?

### ISSUE THREAD

**Issue by paulocoutinhox** [thinks/poisson-disk-sampling#21]
Hi,

I have the stage in my game:

![image](https://github.com/thinks/poisson-disk-sampling/assets/395096/8d8ad604-0b45-41e7-8192-cdca1eaf1e9f)

I have a custom polygon form and i need generate random positions inside this polygon where my obstacles have custom size and can't collide inside it. Always in random position.

This is my current algorithm (but not poison implementation):

![image](https://github.com/thinks/poisson-disk-sampling/assets/395096/99b6484f-1fe1-48f0-9a94-5fdffee15667)

How can i do it? Is possible with your code? The most different thing is that every placed object have their custom size too.

Thanks.

**Comment by thinks** [comment]
You would have to do it in several passes. So maybe you could generate the large object positions first, and then use those to "clip" the smaller positions. I don't think the Poisson distribution methods are well-suited for "multiple radii" scattering problems out-of-the-box.

I will close this, since it is not really a question about the code itself.
