### ISSUE TITLE
Adaptive sampling?

### ISSUE THREAD

**Issue by VarShankar** [thinks/poisson-disk-sampling#3]
This code has been extremely useful. Do you have any suggestions on how to modify this code for adaptive sampling, where the radius varies smoothly across the hypercube, or for the case where one wants more nodes along one or more of the spatial dimensions?

On a side note, if I want to distribute this code with my library, what's the best way to do so? Can I include your header in my library, or should I ask people to get the header from you? I want to do this right :)

**Comment by thinks** [comment]
Hi, glad you like this implementation! I think it would be "fairly" straight-forward to experiment with adaptive sampling. What you need to do is (1) modify the function RandAnnulusSample so that it corresponds to the shape you have in mind, e.g. an ellipsoid; (2) modify ExistingSampleWithinRadius so that it can enforce your criteria. This is not trivial to do, but should be possible. 

There are two main options for distribution. First you can just paste in my header file, which is fine. Slightly more elegant might be to add this repository as a submodule in your repository (google "git submodule" to find plenty of information on how to do this). 

If you want to support me I'd be happy if you gave this repository a Star, or Forked it (which might be a good idea anyhow if you want to experiment).

**Comment by thinks** [comment]
The distance metric as it is implemented assumes symmetry in all dimensions (hyper-spherical samples). If you wish to break this symmetry you must account for it in (at least) the two places I mentioned. I didn't have that extension in mind when writing the code, and if I were to do it myself I might try adding something like a metric class to handle these cases.

**Comment by VarShankar** [comment]
As discussed, I forked the repo. After a quick chat with Bridson, it appears that the best approach is to simply rescale the domain, set the radius to 1.0, proceed with your algorithm/implementation, then rescale the samples back at the end. 

I reopened the issue only to ask: how do I merge this back into your repo? I'm not too familiar with GitHub.

**Comment by thinks** [comment]
Glad you found a good solution! From your forked repo you should be able to create a 'Pull Request' back into my repo. I will need to add a list of contributors! :)

**Comment by VarShankar** [comment]
I now also have a version that works with variable radii by taking a functor (sort of) from the programmer. I will fold all this in via the pull request mechanism.

**Comment by thinks** [comment]
Sorry for late response, I'm quite busy at the moment. I'd be happy to review your pull request when you feel ready.
